### ISSUE TITLE
Im unable to install the module

### ISSUE THREAD

**Issue by Shephiroth** [luc-demeyer/noviat-apps#12]
Hello. Im unable to install the module.

Report:

```
2016-03-04 16:19:23,194 796 ERROR clean06 openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "C:\Users\openerp\odoo-8.0-20151103\openerp\http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Users\openerp\odoo-8.0-20151103\openerp\http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "C:\Users\openerp\odoo-8.0-20151103\openerp\http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Users\openerp\odoo-8.0-20151103\openerp\service\model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Users\openerp\odoo-8.0-20151103\openerp\http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "C:\Users\openerp\odoo-8.0-20151103\openerp\http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "C:\Users\openerp\odoo-8.0-20151103\openerp\http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "C:\Users\openerp\odoo-8.0-20151103\openerp\addons\web\controllers\main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "C:\Users\openerp\odoo-8.0-20151103\openerp\addons\web\controllers\main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "C:\Users\openerp\odoo-8.0-20151103\openerp\api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "C:\Users\openerp\odoo-8.0-20151103\openerp\addons\base\module\module.py", line 447, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "C:\Users\openerp\odoo-8.0-20151103\openerp\api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "C:\Users\openerp\odoo-8.0-20151103\openerp\addons\base\module\module.py", line 495, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "C:\Users\openerp\odoo-8.0-20151103\openerp\modules\registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "C:\Users\openerp\odoo-8.0-20151103\openerp\modules\loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "C:\Users\openerp\odoo-8.0-20151103\openerp\modules\loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "C:\Users\openerp\odoo-8.0-20151103\openerp\modules\loading.py", line 156, in load_module_graph
    registry.setup_models(cr, partial=True)
  File "C:\Users\openerp\odoo-8.0-20151103\openerp\modules\registry.py", line 194, in setup_models
    model._setup_fields(cr, SUPERUSER_ID)
  File "C:\Users\openerp\odoo-8.0-20151103\openerp\api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "C:\Users\openerp\odoo-8.0-20151103\openerp\api.py", line 345, in old_api
    result = method(recs, *args, **kwargs)
  File "C:\Users\openerp\odoo-8.0-20151103\openerp\models.py", line 3005, in _setup_fields
    field.setup(self.env)
  File "C:\Users\openerp\odoo-8.0-20151103\openerp\fields.py", line 453, in setup
    self._setup_related(env)
  File "C:\Users\openerp\odoo-8.0-20151103\openerp\fields.py", line 1341, in _setup_related
    super(Selection, self)._setup_related(env)
  File "C:\Users\openerp\odoo-8.0-20151103\openerp\fields.py", line 500, in _setup_related
    field = recs._fields[name]
AttributeError: 'bool' object has no attribute '_fields'
```

After a little search i found the related field is found on model payment.mode, field payment_order_type. I have located that module on account_banking_payment_export, [github code](https://github.com/OCA/bank-payment)   [odoo module](https://www.odoo.com/apps/modules/8.0/account_banking_payment_export/)
Im using verision 8.0.0.1.166 of the module.

**Comment by luc-demeyer** [comment]
Which noviat module did you try to install ?
Can you also let me know which are the other modules active on the same database ?

**Comment by Shephiroth** [comment]
Hello. Sorry for the weekend.

Im trying to install account_pain.
Tried to install on empty database, it works. Should be some incompatibility with other module. Ill find it.
